# Example device set for SG313 fixtures. Edit to match your wiring/ports.
devices:
  - name: psu
    driver: { module: fixturekit.drivers.korad_kd3005p, class: KoradKD3005P }
    init: { port: /dev/ttyACM0, baud: 9600 }
  - name: adc1
    driver: { module: fixturekit.drivers.ads1115, class: ADS1115 }
    init: { i2c_bus: 1, addr: 0x48 }
  - name: adc2
    driver: { module: fixturekit.drivers.ads1115, class: ADS1115 }
    init: { i2c_bus: 1, addr: 0x4B }
  - name: ina_vin
    driver: { module: fixturekit.drivers.ina219, class: INA219 }
    init: { i2c_bus: 1, addr: 0x40, shunt_ohms: 0.1, current_lsb: 0.0005 }
  - name: ina_chg
    driver: { module: fixturekit.drivers.ina219, class: INA219 }
    init: { i2c_bus: 1, addr: 0x41, shunt_ohms: 0.1, current_lsb: 0.0005 }
  - name: relays
    driver: { module: fixturekit.drivers.mcp23008_rl40002, class: RL40002 }
    init: { i2c_bus: 1, addr: 0x20 }
  - name: digipot
    driver: { module: fixturekit.drivers.mcp4151, class: MCP4151 }
    init: { spi_bus: 0, spi_dev: 0 }
